# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

dist: trusty
language: python
python: "3.5"


addons:
  firefox: latest

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.19.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  # code below is taken from http://conda.pydata.org/docs/travis.html
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib pandas pytest h5py
  - source activate test-environment

  # install PIL for preprocessing tests
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      conda install pil;
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.5" ]]; then
      conda install Pillow;
    fi

  - pip install --user codecov
  - pip install pytest-cov
  - pip install -e .[test]

  # install TensorFlow (CPU version).
  - pip install tensorflow

jobs:
    include:
        - script: pytest -vls --cov=picasso
        - script: pytest -vls ./integration_tests/

after_success:
  - codecov
